import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Dima',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'GeForce RTX 3090',
      slug: 'GeForce-RTX-3090',
      category: 'Відеокарти',
      image: '/images/p1.jpg', // 679px × 829px
      price: 1499,
      countInStock: 10,
      brand: 'Nvidia',
      rating: 4.5,
      numReviews: 10,
      description: "архітектура Ampere, кількість ядер CUDA 10496, частота ядра 1395 МГц, частота Boost 1695 МГц, обсяг пам'яті 24 ГБ GDDR6X, шина пам'яті 384 біти, пропускна здатність пам'яті 936 ГБ/с, підтримка швидкості трасування променів, підтримка технології DLSS",
    },
    {
      // _id: '2',
      name: 'Apple MacBook Air 13 M1 256GB 2020',
      slug: 'Apple-MacBook-Air-13-M1-256GB-2020',
      category: 'Ноутбуки',
      image: '/images/p2.jpg',
      price: 1750,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: "Операційна система: macOS,Дисплей: 13,3-дюймовий Retina-дисплей з роздільною здатністю 2560 x 1600,Процесор: Apple M1 з 8-ядерним CPU та 8-ядерним GPU,Обсяг оперативної пам'яті: 8 ГБ,Обсяг накопичувача: 256 ГБ SSD,Графічний процесор: 8-ядерний GPU,Підтримка Wi-Fi та Bluetooth,Роз'єми: 2 порти Thunderbolt 3 / USB 4, аудіороз'єм 3,5 мм,Камера: 720p FaceTime HD,Сканер Touch ID для аутентифікації користувача,",
    },
    {
      // _id: '3',
      name: 'AMD Radeon RX 6900 XT',
      slug: 'AMD-Radeon-RX-6900-XT',
      category: 'Відеокарти',
      image: '/images/p3.jpg',
      price: 1500,
      countInStock: 15,
      brand: 'AMD',
      rating: 4.5,
      numReviews: 14,
      description: "AMD Radeon RX 6900 XT - це потужна відеокарта з 80 обчислювальними блоками, 16 ГБ пам'яті GDDR6, швидкістю графічної пам'яті 16 Гбіт/с і підтримкою трасування променів.",
    },
    {
      // _id: '4',
      name: 'Ноутбук Acer Nitro 5 ',
      slug: 'Ноутбук-Acer-Nitro-5 ',
      category: 'Ноутбук',
      image: '/images/p4.jpg',
      price: 1000,
      countInStock: 5,
      brand: 'Acer',
      rating: 4.5,
      numReviews: 10,
      description: "це потужний ігровий лептоп з 17,3-дюймовим Full HD дисплеєм, процесором Intel Core i5-11400H, 8 ГБ оперативної пам'яті, відеокартою NVIDIA GeForce RTX 3050 і 512 ГБ SSD-накопичувачем.",
    },
    {
      name: 'Intel Core i9-13900K',
      slug: 'Intel-Core-i9-13900K',
      category: 'Процесор',
      image: '/images/p5.jpg',
      price: 600,
      countInStock: 5,
      brand: 'Intel',
      rating: 4.5,
      numReviews: 10,
      description: "це потужний 12-ядерний процесор з базовою частотою 3,0 ГГц, 36 МБ кеш-пам'яті та підтримкою технології гіперпотокування, що забезпечує високу продуктивність при виконанні важких завдань.      ",
    },
    {
      name: 'AMD Ryzen 9 5950X',
      slug: 'AMD-Ryzen-9-5950X',
      category: 'Процесор',
      image: '/images/p6.jpg',
      price: 850,
      countInStock: 5,
      brand: 'AMD',
      rating: 4.5,
      numReviews: 10,
      description: " 16-ядерний процесор з базовою частотою 3,4 ГГц, 72 МБ кеш-пам'яті, підтримкою технології гіперпотокування та високою продуктивністю завдяки архітектурі Zen 3.",
    },
    {
      name: 'клавіатура 2E KS230 WL Black',
      slug: 'клавіатура-2E-KS23-WL-Black',
      category: 'Клавіатура',
      image: '/images/p7.jpg',
      price: 20,
      countInStock: 5,
      brand: '2Е',
      rating: 3,
      numReviews: 10,
      description: "Беспровідна клавіатура 2E KS230 WL Black (2E-KS230WB) має стильний дизайн, підтримку підключення через USB-адаптер, імпульсну технологію для збереження заряду батареї, мультимедійні клавіші та діапазон дії до 10 метрів.      ",
    },
    {
      name: 'Logitech MX Mechanical Wireless Illuminated Performance Graphite',
      slug: 'Logitech-MX-Mechanical-Wireless-Illuminated-Performance-Graphite',
      category: 'Клавіатура',
      image: '/images/p8.jpg',
      price: 100,
      countInStock: 5,
      brand: 'Logitech',
      rating: 4,
      numReviews: 10,
      description: "Беспровідна клавіатура Logitech MX Mechanical Wireless Illuminated Performance Graphite (920-010757) має механічні перемикачі, підсвічування клавіш, вбудований USB-хаб та можливість підключення до трьох пристроїв одночасно.",
    },
    {
      name: 'Acer S220HQL',
      slug: 'Acer-S220HQL',
      category: 'Монітор',
      image: '/images/p9.jpg',
      price: 10,
      countInStock: 5,
      brand: 'Acer',
      rating: 2,
      numReviews: 10,
      description: "Монитор Б-классу Acer S220HQL - 22-дюймовий, з роздільною здатністю 1920x1080, з часом відгуку 5 мс, з контрастністю 1000:1 та яскравістю 200 кд/м².",
    },
    {
      name: 'Монитор 27" LG UltraFine 27UL500-W -- 4К IPS / 8-Bit+FRC / sRGB 99% / HDR10 / AMD FreeSync / Flicker-Free',
      slug: 'LG-UltraFine-27UL500-W',
      category: 'Монітор',
      image: '/images/p10.jpg',
      price: 100,
      countInStock: 5,
      brand: 'LG',
      rating: 4,
      numReviews: 10,
      description: "Монитор LG UltraFine 27UL500-W має діагональ 27 дюймів, підтримує роздільну здатність 4К, використовує технологію IPS, має 8-Bit+FRC кольорову глибину, охоплює 99% сRGB, підтримує HDR10, AMD FreeSync та Flicker-Free технології.      ",
    },
  ],
};
export default data;
